---
title: "Class_201502_overview"
author: "coop711"
date: "2015년 9월 7일"
output: html_document
---

* 8월31일과 9월2일 현황

```{r}
setwd("~/Dropbox/Works/Class/Statistics/201502")
options(width=180)
load("class0906.rda")
class0831[, -c(1:3, 5:6)]
class0902[, -c(1:3, 5:6)]
ls()
```

* 개강초기 소속 단과대학 파악

```{r}
class0831$dept <- class0831$"학과"
class0831$college <- with(class0831, ifelse(dept %in% c("국어국문학과", "영어영문학과", "러시아학과", "철학과", "사학과"), "인문대학", ifelse(dept %in% c("사회학과", "심리학과", "사회복지학부", "언론정보학부", "언론", "방송통신", "법학", "정치행정", "정치행정학과","법행정학부", "디지털콘텐츠", "광고홍보학과"), "사회과학대학", ifelse(dept %in% c("경제학과", "경영학부", "경영학", "의료경영", "재무금융학과"), "경영대학", ifelse(dept %in% c("전자물리학과", "생명과학과", "바이오메디컬학과", "환경생명공학과", "언어병리학", "체육학부", "체육학", "재활운동학"), "자연과학대학", ifelse(dept %in% c("전자공학과", "컴퓨터공학과", "융합소프트웨어학과"), "정보전자공과대학", "의과대학"))))))
class0831$college.f <- factor(class0831$college, levels=c("인문대학", "사회과학대학", "경영대학", "자연과학대학", "정보전자공과대학", "의과대학"))
str(class0831)
with(class0831, data.frame(dept, college.f))
with(class0831, table(college.f))
library(ggplot2)
ggplot(class0831, aes(x=college.f)) + geom_bar(fill="red", alpha=0.5) +
  theme_bw() +
  theme(axis.text.x=element_text(family="HCR Dotum LVT"),
        axis.title.x=element_text(family="HCR Dotum LVT"),
        axis.title.y=element_text(family="HCR Dotum LVT")) +
  xlab("단과대학") + ylab("수강인원")
options(digits=2)
with(class0831, prop.table(table(college.f)))
```

* 9월2일 시점 소속 단과대학 파악

```{r}
class0902$dept <- class0902$"학과"
class0902$college <- with(class0902, ifelse(dept %in% c("국어국문학과", "영어영문학과", "러시아학과", "철학과", "사학과"), "인문대학", ifelse(dept %in% c("사회학과", "심리학과", "사회복지학부", "언론정보학부", "언론", "방송통신", "법학", "정치행정", "정치행정학과","법행정학부", "디지털콘텐츠", "광고홍보학과"), "사회과학대학", ifelse(dept %in% c("경제학과", "경영학부", "경영학", "의료경영", "재무금융학과"), "경영대학", ifelse(dept %in% c("전자물리학과", "생명과학과", "바이오메디컬학과", "환경생명공학과", "언어병리학", "체육학부", "체육학", "재활운동학"), "자연과학대학", ifelse(dept %in% c("전자공학과", "컴퓨터공학과", "융합소프트웨어학과"), "정보전자공과대학", "의과대학"))))))
class0902$college.f <- factor(class0902$college, levels=c("인문대학", "사회과학대학", "경영대학", "자연과학대학", "정보전자공과대학", "의과대학"))
str(class0902)
with(class0902, data.frame(dept, college.f))
with(class0902, table(college.f))
library(ggplot2)
ggplot(class0902, aes(x=college.f)) + geom_bar(fill="red", alpha=0.5) +
  theme_bw() +
  theme(axis.text.x=element_text(family="HCR Dotum LVT"),
        axis.title.x=element_text(family="HCR Dotum LVT"),
        axis.title.y=element_text(family="HCR Dotum LVT")) +
  xlab("단과대학") + ylab("수강인원")
options(digits=2)
with(class0902, prop.table(table(college.f)))
```


* 두 자료 합쳐 보기

```{r}
library(plyr)
class.join <- join(class0831, class0902, by="학.직.번", type="full")
class.join[, -c(1:3, 5:6)]
```

* 일부 변수명 조정

```{r}
names(class.join)
names(class.join)[15] <- "after"
names(class.join)[16] <- "sejong"
names(class.join)
```

* 산국궤 수업 전과 수업 후의 인식 차이 계산

```{r}
class.join$diff <- class.join$after - class.join$before
table(class.join$diff, useNA="ifany")
```

* paired t.test 해 보겠지만 의미가 있는지 생각해 볼 것.

```{r}
t.test(class.join$diff, alternative="greater")
```

* 세종대왕에 대한 인식 정도 (before)

```{r}
table(class.join$sejong, useNA="ifany")
class.join$sejong.tf <- factor(ifelse(class.join$sejong == "가나다", "Right", "Wrong"))
table(class.join$sejong.tf, useNA="ifany")
options(digits=2)
prop.table(table(class.join$sejong.tf, useNA="ifany"))*100
```

* e-mail 주소의 특성

```{r}
table(mail.com)
mail.df <- as.data.frame(table(mail.com, useNA="ifany"), stringsAsFactors=TRUE)
mail.df
mail.df.order <- mail.df[order(mail.df$Freq, decreasing=TRUE), ]
mail.df.order
```

* 성씨의 분포

```{r}
table(class.join$f.name, useNA="ifany")
f.name.df <- as.data.frame(table(class.join$f.name, useNA="ifany"), stringsAsFactors=TRUE)
f.name.df.order <- f.name.df[order(f.name.df$Freq, decreasing=TRUE),]
f.name.df.order
```


* 일단 자료를 갈무리하고,

```{r}
save.image(file="class0906.rda")
rm(list=ls())
```

## 9월 7일 자료 분석

```{r}
load("class0908.rda")
ls()
str(class0907)
```

# 소속 단과대학 파악

```{r}
class0907$college <- with(class0907, ifelse(dept %in% c("국어국문학과", "영어영문학과", "러시아학과", "철학과", "사학과"), "인문대학", ifelse(dept %in% c("사회학과", "사회복지학부", "언론정보학부", "언론", "방송통신", "법학", "정치행정", "디지털콘텐츠", "광고홍보학과"), "사회과학대학", ifelse(dept %in% c("경제학과", "경영학부", "경영학", "재무금융학과"), "경영대학", ifelse(dept %in% c("전자물리학과", "바이오메디컬학과", "체육학부", "체육학"), "자연과학대학", "정보전자공과대학")))))
class0907$college.f <- factor(class0907$college, levels=c("인문대학", "사회과학대학", "경영대학", "자연과학대학", "정보전자공과대학"))
str(class0907)
with(class0907, data.frame(dept, college.f))
with(class0907, table(college.f))
ggplot(class0907, aes(x=college.f)) + geom_bar(fill="red", alpha=0.5) +
  theme_bw() +
  theme(axis.text.x=element_text(family="HCR Dotum LVT"),
        axis.title.x=element_text(family="HCR Dotum LVT"),
        axis.title.y=element_text(family="HCR Dotum LVT")) +
  xlab("단과대학") + ylab("수강인원")
options(digits=2)
with(class0907, prop.table(table(college.f)))
```

* 자료 정리

```{r}
save.image(file="class0908.rda")
rm(list=ls())
```