---
title: "Class_BFI_MI"
author: "coop711"
date: "2015년 6월 2일"
output: html_document
---

Data Reading
------------

`join()`을 사용하기 위하여 `plyr` 패키지는 사전에 등록

```{r}
library(plyr)
```
필수 자료 읽어들이기

```{r}
load("./BFI_MI_1502.rda")
ls()
str(BFI)
str(MI)
str(class.roll)
options(width=132)
```

Big Five Inventory First
------------------------

계산의 편의를 돕기 위해 `BFI` 자료를 검색 목록에 등록하고, 점수 합산.

```{r}
attach(BFI)
E.score<-E1+E2
N.score<-N1+N2
C.score<-C1+C2
A.score<-A1+A2+A3
O.score<-O1+O2+O3
```

data frame으로 정리하고, 한글 명칭 부여

```{r}
BFI.score<-data.frame(E.score, N.score, C.score, A.score, O.score)
BFI.type.kr<-c("외향성", "신경성", "성실성", "친화성", "개방성")
dimnames(BFI.score)<-list(ID, BFI.type.kr)
BFI.score
```

점수에 따른 수준 판정

```{r}
E.level.kr<-ifelse(E.score <= 4, "하", ifelse(E.score <=6, "중하", ifelse(E.score <=8, "중상", "상")))
N.level.kr<-ifelse(N.score <= 4, "하", ifelse(N.score <=6, "중하", ifelse(N.score <=8, "중상", "상")))
C.level.kr<-ifelse(C.score <= 4, "하", ifelse(C.score <=6, "중하", ifelse(C.score <=8, "중상", "상")))
A.level.kr<-ifelse(A.score <= 10, "하", ifelse(A.score <=12, "중하", ifelse(A.score <=13, "중상", "상")))
O.level.kr<-ifelse(O.score <= 8, "하", ifelse(O.score <=10, "중하", ifelse(O.score <=12, "중상", "상")))
```

ordered factor 로 구성된 data frame 으로 정리

```{r}
BFI.level<-data.frame(E.level.kr, N.level.kr, C.level.kr, A.level.kr, O.level.kr)
BFI.level.kr<-data.frame(lapply(BFI.level, function(x) factor(x, levels=c("하", "중하", "중상", "상"), ordered=TRUE)))
dimnames(BFI.level.kr)<-list(ID, BFI.type.kr)
BFI.level.kr
```

위 과정은 다음과 같이 사용자 함수와 `mapply()`를 이용하여 다소 줄일 수도 있다.

```{r}
criteria<-function(x, a=c(4, 6, 8)){
  ifelse(x<=a[1], "하", ifelse(x<=a[2], "중하", ifelse(x<=a[3], "중상", "상")))
}
a<-list(c(4,6,8), c(4,6,8), c(4,6,8), c(10,12,13), c(8,10,12))
BFI.level.2<-data.frame(mapply(criteria, BFI.score, a=a))
BFI.level.kr.2<-data.frame(lapply(BFI.level.2, function(x) factor(x, levels=c("하", "중하", "중상", "상"), ordered=TRUE)))
dimnames(BFI.level.kr.2)<-list(ID, BFI.type.kr)
BFI.level.kr.2
```

각 성질의 분포를 `table`로 요약

```{r}
BFI.level.table<-sapply(BFI.level.kr, table)
BFI.level.table
```

출석부에 합치기
---------------

`rownames`으로 되어 있는 학번(`ID`)을 `ID`로 돌리고, `row.names`는 일련번호로 정리

```{r}
BFI.level.kr.2<-data.frame(ID = ID, BFI.level.kr, row.names=1:nrow(BFI.level.kr))
BFI.level.kr.2
```

전체 출석부로 통합하고, 실험에 참여하지 않은 사람들은 `<NA>`로 표시.

```{r}
BFI.full.kr<-join(class.roll, BFI.level.kr.2, by="ID")
BFI.full.kr
```

잊지 말고 `detach()`

```{r}
detach(BFI)
```

다중지능 점수 분석
------------------

다중지능 점수를 합산하기 위하여 `for` loop를 활용.

```{r}
A<-matrix(numeric(0), nrow=nrow(MI), ncol=8)
for(j in 1:8) {A[,j]<-MI[,j+1]
for(i in 1:6) {
A[,j]<-A[,j]+MI[, j+i*8]
}}
MI.score.kr<-A
MI.names.kr<-c("음악", "신체운동", "논리수학", "공간", "언어", "인간친화", "자기성찰", "자연친화")
dimnames(MI.score.kr)<-list(MI$ID, MI.names.kr)
MI.score.kr
```

각 지능을 점수 순으로 배열

```{r}
MI.order.kr<-apply(MI.score.kr, 1, order, decreasing = TRUE)
MI.sort.kr<-matrix(MI.names.kr[MI.order.kr], ncol=8, byrow=T, dimnames=list(MI$ID, paste("제",1:8,"순위", sep="")))
MI.sort.kr
```

출석부에 합치기
-------------

`rownames`를 `ID`로 돌리고, `row.names`는 일련번호로 정리

```{r}
MI.sort.kr.2<-data.frame(ID = MI$ID, MI.sort.kr, row.names=1:nrow(MI.sort.kr))
MI.sort.kr.2
```

출석부에 통합

```{r}
MI.sort.full.kr<-join(class.roll, MI.sort.kr.2, by="ID")
MI.sort.full.kr
```

두 data frame을 하나로
----------------------

Merge 2 data frames into one

```{r}
BFI.MI.full<-data.frame(BFI.full.kr, MI.sort.full.kr[, 3:5])
BFI.MI.full
```

이름을 빼고 학번만 표시

```{r}
BFI.MI.full.ID<-BFI.MI.full[,-2]
BFI.MI.full.ID
```

결석생 확인
-----------

BFI결석생

```{r}
BFI.present<-which(class.roll$ID %in% BFI$ID)
BFI.absent<-(1:nrow(class.roll))[-BFI.present]
BFI.absent
class.roll$ID[BFI.absent]
class.roll$Name[BFI.absent]
```

MI 결석생

```{r}
MI.present<-which(class.roll$ID %in% MI$ID)
MI.absent<-(1:nrow(class.roll))[-MI.present]
MI.absent
class.roll$ID[MI.absent]
class.roll$Name[MI.absent]
```